// <auto-generated />
using System;
using LocalSpaceCloud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalSpaceCloud.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LocalSpaceCloud.Models.DataModels.BinEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestorePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemEntityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SystemEntityType");

                    b.HasIndex("UserID");

                    b.ToTable("BinEntities");
                });

            modelBuilder.Entity("LocalSpaceCloud.Models.DataModels.SystemEntityTypeValue", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SystemEntityTypes");

                    b.HasData(
                        new
                        {
                            ID = 0,
                            Description = "File system cataloging structure which contains references to other computer files, and possibly other directories",
                            Name = "Directory"
                        },
                        new
                        {
                            ID = 1,
                            Description = "Computer resource for recording data discretely in a computer storage device",
                            Name = "File"
                        },
                        new
                        {
                            ID = 2,
                            Description = "An archive is an accumulation of historical records",
                            Name = "Archive"
                        });
                });

            modelBuilder.Entity("LocalSpaceCloud.Models.DataModels.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocalSpaceCloud.Models.DataModels.BinEntity", b =>
                {
                    b.HasOne("LocalSpaceCloud.Models.DataModels.SystemEntityTypeValue", "SystemEntityTypeValue")
                        .WithMany()
                        .HasForeignKey("SystemEntityType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalSpaceCloud.Models.DataModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemEntityTypeValue");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
